version: "3.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: jmeter-elastic-apm-elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: jmeter-elastic-apm-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  apm:
    image: docker.elastic.co/apm/apm-server:7.6.2
    container_name: jmeter-elastic-apm-apm
    command: --strict.perms=false -e
    ports:
      - "8200:8200"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - "./apm/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro"
    depends_on:
      - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: jmeter-elastic-apm-logstash
    ports:
      - "12201:12201/udp"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - "./logstash/pipeline/:/usr/share/logstash/pipeline/"
      - "./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
    depends_on:
      - elasticsearch
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.6.2
    container_name: jmeter-elastic-apm-metricbeat
    hostname: jmeter-elastic-apm-metricbeat
    user: root
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./metricbeat/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
    environment:
      - KIBANA_HOST=kibana:5601
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    container_name: jmeter-elastic-apm-filebeat
    hostname: jmeter-elastic-apm-filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./elastic/filebeat/log:/var/log/filebeat
      - ../jmeter/results/:/usr/share/jmeter/
      - ../spring-boot-app/logs/:/usr/share/spring-boot-logs/
    environment:
      - KIBANA_HOST=kibana:5601
    command: ""
    depends_on:
      - logstash
