spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://127.0.0.1:5432/jmeter-elastic-apm
    username: jmeter-elastic-apm-postgres-user
    password: 12345abcde
  redis:
    host: 127.0.0.1
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update


  cache:
    redis:
      time-to-live: 100000